server:
  port: 8888

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: test
        uri: http://www.baidu.com/
        predicates:
          - Path=/zhang/**