


server:
  port: 8765

spring:
  application:
    name: feign-ribbon

eureka:
  client:
    serviceUrl:
      defualtZone: http://localhost:8761/eureka/


# 加入断路器, 当服务响应多次超时或者服务不可用的时候,返回指定callback
feign:
  hystrix:
    enabled: true