spring:
  application:
    name: eureka-client # 该名字是服务器之间选择的标志


server:
  port: 8762
  servlet:
    context-path: /client


eureka:
  client:
    serviceUrl:
      # server服务器
      defaultZone: http://localhost:8761/server/eureka/