

server:
  port: 18761

spring:
  application:
    name: pear-eureka-peer1

eureka:
  instance:
    hostname: 119.29.240.47  # 部署到119测试服务器,注意prefer-ip-address=true才能直接写ip地址, 不然的去/etc/hosts中修改
  client:
    # 通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
    # 在未设置defaultZone的情况下，注册中心在本例中的默认地址就是http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://139.199.19.34:28762/eureka/





