spring:
  application:
    name: my-eureka-service # 该名字是服务器之间选择的标志[服务器会显示为EUREKA-CLIENT]


server:
  port: 8763

eureka:
  client:
    serviceUrl:
      # server服务器
      defaultZone: http://localhost:8761/eureka/