server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/q258523454/springCloudTest
          search-paths: /config-server/src/main/resources
          default-label: master
          username: # 如果Git仓库为公开仓库，可以不填写用户名和密码
          password:
