server:
  port: 8888

# http请求地址和资源文件映射..常用的是: /{application}/{profile}[/{label}]
# 例如http://localhost:8888/config-client2/test, 访问的是config-client2-test.yml文件
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # 配置git仓库地址和配置文件相对路径
          uri: https://github.com/q258523454/springCloudTest
          search-paths: config-server/src/main/config
          # 如果Git仓库为公开仓库，可以不填写用户名和密码
          username:
          password:
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



